# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # SSH key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Sync files to droplet
      - name: Sync files
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ${{ secrets.USER }}@${{ secrets.DROPLET_IP }}:/var/www/html/wp-content/themes/block-test

      - name: Set permissions
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@{{ secrets.DROPLET_IP }} "sudo chown -R www-data:www-data /var/www/html/wp-content/themes/block-test/"
